[header]
path = "config/hawkeye/license-header.txt"

[files]
includes = [
    "src/**/*.rs",
    "tests/**/*.rs",
    "benches/**/*.rs",
    "examples/**/*.rs",
    "build.rs",
    "tools/**/*.py",
]

[props]
inception_year = 2026
